words = [
"anus",
"arse",
"arsehole",
"ass",
"ass-hat",
"ass-jabber",
"ass-pirate",
"assbag",
"assbandit",
"assbanger",
"assbite",
"assclown",
"asscock",
"asscracker",
"asses",
"assface",
"assfuck",
"assfucker",
"assgoblin",
"asshat",
"asshead",
"asshole",
"asshopper",
"assjacker",
"asslick",
"asslicker",
"assmonkey",
"assmunch",
"assmuncher",
"assnigger",
"asspirate",
"assshit",
"assshole",
"asssucker",
"asswad",
"asswipe",
"axwound",
"bampot",
"bastard",
"beaner",
"bitch",
"bitchass",
"bitches",
"bitchtits",
"bitchy",
"blow job",
"blowjob",
"bollocks",
"bollox",
"boner",
"brotherfucker",
"bullshit",
"bumblefuck",
"butt plug",
"butt-pirate",
"buttfucka",
"buttfucker",
"camel toe",
"carpetmuncher",
"chesticle",
"chinc",
"chink",
"choad",
"chode",
"clit",
"clitface",
"clitfuck",
"clusterfuck",
"cock",
"cockass",
"cockbite",
"cockburger",
"cockface",
"cockfucker",
"cockhead",
"cockjockey",
"cockknoker",
"cockmaster",
"cockmongler",
"cockmongruel",
"cockmonkey",
"cockmuncher",
"cocknose",
"cocknugget",
"cockshit",
"cocksmith",
"cocksmoke",
"cocksmoker",
"cocksniffer",
"cocksucker",
"cockwaffle",
"coochie",
"coochy",
"coon",
"cooter",
"cracker",
"cum",
"cumbubble",
"cumdumpster",
"cumguzzler",
"cumjockey",
"cumslut",
"cumtart",
"cunnie",
"cunnilingus",
"cunt",
"cuntass",
"cuntface",
"cunthole",
"cuntlicker",
"cuntrag",
"cuntslut",
"dago",
"damn",
"deggo",
"dick",
"dick-sneeze",
"dickbag",
"dickbeaters",
"dickface",
"dickfuck",
"dickfucker",
"dickhead",
"dickhole",
"dickjuice",
"dickmilk",
"dickmonger",
"dicks",
"dickslap",
"dicksucker",
"dicksucking",
"dicktickler",
"dickwad",
"dickweasel",
"dickweed",
"dickwod",
"dike",
"dildo",
"dipshit",
"doochbag",
"dookie",
"douche",
"douche-fag",
"douchebag",
"douchewaffle",
"dumass",
"dumb ass",
"dumbass",
"dumbfuck",
"dumbshit",
"dumshit",
"dyke",
"fag",
"fagbag",
"fagfucker",
"faggit",
"faggot",
"faggotcock",
"fagtard",
"fatass",
"fellatio",
"feltch",
"flamer",
"fuck",
"fuckass",
"fuckbag",
"fuckboy",
"fuckbrain",
"fuckbutt",
"fuckbutter",
"fucked",
"fucker",
"fuckersucker",
"fuckface",
"fuckhead",
"fuckhole",
"fuckin",
"fucking",
"fucknut",
"fucknutt",
"fuckoff",
"fucks",
"fuckstick",
"fucktard",
"fucktart",
"fuckup",
"fuckwad",
"fuckwit",
"fuckwitt",
"fudgepacker",
"gay",
"gayass",
"gaybob",
"gaydo",
"gayfuck",
"gayfuckist",
"gaylord",
"gaytard",
"gaywad",
"goddamn",
"goddamnit",
"gooch",
"gook",
"gringo",
"guido",
"handjob",
"hard on",
"heeb",
"hell",
"ho",
"hoe",
"homo",
"homodumbshit",
"honkey",
"humping",
"jackass",
"jagoff",
"jap",
"jerk off",
"jerkass",
"jigaboo",
"jizz",
"jungle bunny",
"junglebunny",
"kike",
"kooch",
"kootch",
"kraut",
"kunt",
"kyke",
"lameass",
"lardass",
"lesbian",
"lesbo",
"lezzie",
"mcfagget",
"mick",
"minge",
"mothafucka",
"mothafuckin'",
"motherfucker",
"motherfucking",
"muff",
"muffdiver",
"munging",
"negro",
"nigaboo",
"nigga",
"nigger",
"niggers",
"niglet",
"nut sack",
"nutsack",
"porn",
"paki",
"panooch",
"pecker",
"peckerhead",
"penis",
"penisbanger",
"penisfucker",
"penispuffer",
"piss",
"pissed",
"pissed off",
"pissflaps",
"polesmoker",
"pollock",
"poon",
"poonani",
"poonany",
"poontang",
"porch monkey",
"porchmonkey",
"prick",
"punanny",
"punta",
"pussies",
"pussy",
"pussylicking",
"puto",
"queef",
"queer",
"queerbait",
"queerhole",
"renob",
"rimjob",
"ruski",
"sand nigger",
"sandnigger",
"schlong",
"scrote",
"shit",
"shitass",
"shitbag",
"shitbagger",
"shitbrains",
"shitbreath",
"shitcanned",
"shitcunt",
"shitdick",
"shitface",
"shitfaced",
"shithead",
"shithole",
"shithouse",
"shitspitter",
"shitstain",
"shitter",
"shittiest",
"shitting",
"shitty",
"shiz",
"shiznit",
"skank",
"skeet",
"skullfuck",
"slut",
"slutbag",
"smeg",
"spic",
"spick",
"splooge",
"spook",
"suckass",
"tard",
"testicle",
"thundercunt",
"tit",
"titfuck",
"tits",
"tittyfuck",
"twat",
"twatlips",
"twats",
"twatwaffle",
"unclefucker",
"va-j-j",
"vag",
"vagina",
"vajayjay",
"vjayjay",
"wank",
"wankjob",
"wetback",
"whore",
"whorebag",
"whoreface",
"wop",
]

function urlcheck(url) {
	var params = getUrlVars(url);
	if(params.q != null) {
		return paramscheck(params.q);
	} else if(params.search_query!=null){
		return paramscheck(params.search_query);
	} else {
		return 0;
	}
}

function paramscheck(params) {
	count = 0.0;
	bad = 0.0;
	if(params.includes("+")) {
		params = params.split("+");
	} else {
		params = params.split("%");
	}
	count = params.length;
	for(i=0;i< words.length;i++) {
		if(params.indexOf(words[i])!=-1) {
			bad++;
		}
	}
	return bad/count;
}

function getUrlVars(href)
{
    var vars = [], hash;
    var hashes = href.slice(href.indexOf('?') + 1).split('&');
    for(var i = 0; i < hashes.length; i++)
    {
        hash = hashes[i].split('=');
        vars.push(hash[0]);
        vars[hash[0]] = hash[1];
    }
    return vars;
}

console.log(urlcheck("https://www.youtube.com/results?search_query=AAnother+search"));
console.log(urlcheck("https://www.google.co.in/search?q=porn&rlz=1C1CHZL_enIN700IN700&oq=porn&aqs=chrome.0.69i59j69i60l3j69i59l2.2057j0j4&sourceid=chrome&ie=UTF-8#q=porn+and+sex"));
console.log(urlcheck("https://www.google.co.in/search?q=shit+bro+sex&rlz=1C1CHZL_enIN700IN700&oq=shit+bro+sex&aqs=chrome..69i57.4549j0j9&sourceid=chrome&ie=UTF-8"));
console.log(urlcheck("http://www.bing.com/search?q=Hey+how+are+you+my+friend%3F&qs=n&form=QBLH&sp=-1&pq=hey+how+are+you+my+friend&sc=0-25&sk=&cvid=7E1D4074F69C45D781A157BAA3C3FC23"));
console.log(urlcheck("https://www.youtube.com/results?search_query=What+is+up"));
console.log(urlcheck("https://github.com/rajatjain1997/Content-Rectifier-II"));
console.log(urlcheck("https://www.google.com/search?site=&tbm=isch&source=hp&biw=1366&bih=662&q=Hey+hi&oq=Hey+hi&gs_l=img.3..0l10.1060.2748.0.3014.7.7.0.0.0.0.174.319.0j2.2.0....0...1ac.1.64.img..5.2.319.0.BqANwFQUI_Y"));
console.log(urlcheck("https://www.google.com/search?site=&tbm=isch&source=hp&biw=1366&bih=662&q=Hey+hi&oq=Hey+hi&gs_l=img.3..0l10.1060.2748.0.3014.7.7.0.0.0.0.174.319.0j2.2.0....0...1ac.1.64.img..5.2.319.0.BqANwFQUI_Y#tbm=isch&q=Hey+hi+porn"));